# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: license_management_system_development

test:
  <<: *default
  database: license_management_system_test

production:
  <<: *default
  database: license_management_system_production
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>